"""empty message

Revision ID: 3b2877bb6194
Revises: 
Create Date: 2024-04-26 14:52:34.757035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2877bb6194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Items_itemname'), ['itemname'], unique=True)

    op.create_table('Representative',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('Representative', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Representative_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Representative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Representative_username'))

    op.drop_table('Representative')
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Items_itemname'))

    op.drop_table('Items')
    # ### end Alembic commands ###
