"""empty message

Revision ID: 3ba2a54e112a
Revises: 10826f76577b
Create Date: 2024-04-27 20:46:51.755581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba2a54e112a'
down_revision = '10826f76577b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_representative', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Log', schema=None) as batch_op:
        batch_op.drop_column('log_representative')

    # ### end Alembic commands ###
