"""empty message

Revision ID: 6b5f101fe5d3
Revises: 
Create Date: 2024-04-27 17:21:42.500538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5f101fe5d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Items_itemname'), ['itemname'], unique=True)

    op.create_table('Log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('log_itemname', sa.String(), nullable=True),
    sa.Column('log_item_quantity', sa.Integer(), nullable=True),
    sa.Column('log_item_quantity_now', sa.Integer(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('Log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Log_log_itemname'), ['log_itemname'], unique=False)

    op.create_table('Representative',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('useremail', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('Representative', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Representative_useremail'), ['useremail'], unique=True)
        batch_op.create_index(batch_op.f('ix_Representative_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Representative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Representative_username'))
        batch_op.drop_index(batch_op.f('ix_Representative_useremail'))

    op.drop_table('Representative')
    with op.batch_alter_table('Log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Log_log_itemname'))

    op.drop_table('Log')
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Items_itemname'))

    op.drop_table('Items')
    # ### end Alembic commands ###
